config/routes.rb
Rails.application.routes.draw do
  get 'enrollments/new'
  post 'enrollments/create'
  get 'courses/get_all_dont_use'
  match 'courses/get_all_free_by_student', via: [:get, :post]

  resources :courses

  resources :students

  get 'welcome/index'

  root 'welcome#index'

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms
  validates :name, presence: true
  validates :description, presence: true
  validates :status, presence: true  
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms
  validates :name, presence: true
  validates :register_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @course }
      else
        format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end

  def get_all_free_by_student
    @courses = Course.where.not(id: Classroom.where(:student_id => params['student_id']).select(:course_id))
    render :json => @courses
  end

  def get_all_dont_use
    @courses = Course.where.not(id: Classroom.select(:course_id))
    render :json => @courses
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def new
    @all_courses = Course.all
    @all_students = Student.all
  end

  def create
    # render :text => params[:entry_at]
    Classroom.create student_id: params[:student_id], course_id: params[:course_id], entry_at: params[:entry_at]
    redirect_to root_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @total_students = Student.all.count
    @total_courses = Course.all.count
    @last_enroolment = Classroom.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/courses/_form.html.erb
<%= simple_form_for(@course, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :status, as: :boolean, checked_value: 1, unchecked_value: 0 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.description %></td>
        <td><span class="glyphicon <%= course.status==1?'glyphicon-ok':'glyphicon-remove'%>" > </span></td>
        <td><%= link_to 'Show', course, :class => 'btn btn-mini'  %></td>
        <td><%= link_to 'Edit', edit_course_path(course), :class => 'btn btn-mini'  %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, :class => 'btn btn-primary' %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Status:</strong>
  <span class="glyphicon <%= @course.status==1?'glyphicon-ok':'glyphicon-remove'%>" > </span>
</p>

<% if (@course.classrooms) %>
  <div class="panel panel-default">
    <div class="panel-heading">Students:</div>
    <div class="panel-body">
      <ul>
        <% @course.classrooms.each do |classroom| %>
          <li> <%= classroom.student.name %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/enrollments/new.html.erb
<h1>New Enrollment</h1>

<%= form_tag("/enrollments/create", method: "post") do %>
  <p>
    <%= label_tag(:student_id, "Students:") %>
    <%= select_tag "student_id", options_from_collection_for_select(@all_students, "id", "name"), {prompt: 'Select Student'} %>
  </p>

  <p>
    <%= label_tag(:course_id, "Courses:") %>
    <%= select_tag "course_id" %>
  </p>

  <p>
    <%= label_tag(:entry_at, "Entry At:") %>
    <%= date_field_tag "entry_at", Date.today %>
  </p>

  <%= submit_tag("Confirmar", :class => 'btn btn-success')%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProficiencyTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class='panel-heading'>
      <h1 class='panel-title'> School App</h3>
    </div>
    <h1></h1>
    <div class='container'>
      <nav class='navbar navbar-default'>
        <div class='container-fluid'>
          <ul class='nav navbar-nav'>
            <li> <%= link_to "Home", root_path %>
            <li> <%= link_to "Student", students_path %>
            <li> <%= link_to "Course", courses_path %>
            <li> <%= link_to "New Enrollment", enrollments_new_path %>
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <div id="main">
    <div class='container'>
      <%= yield %>
    </div>
  </div>

  <footer>
    <div class='panel-footer'>
      2016 - http://rocky-beyond-26838.herokuapp.com/
    </div>
  </footer>
</body>
</html>

app/views/students/_form.html.erb
<%= simple_form_for(@student, html: {class: 'form-horizontal' }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :register_number %>
    <%= f.input :status, as: :boolean, checked_value: 1, unchecked_value: 0 %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Listing students</h1>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Register number</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.register_number %></td>
        <td><span class="glyphicon <%= student.status==1?'glyphicon-ok':'glyphicon-remove'%>" > </span></td>
        <td><%= link_to 'Show', student, :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_student_path(student), :class => 'btn btn-mini' %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, :class => 'btn btn-primary' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Register number:</strong>
  <%= @student.register_number %>
</p>

<p>
  <strong>Status:</strong>
  <span class="glyphicon <%= @student.status==1?'glyphicon-ok':'glyphicon-remove'%>" > </span>
</p>

<% if (@student.classrooms) %>
  <div class="panel panel-default">
    <div class="panel-heading">Courses:</div>
    <div class="panel-body">
      <ul>
        <% @student.classrooms.each do |classroom| %>
          <li> <%= classroom.course.name %>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Total Students:</div>
  <div class="panel-body"><%= @total_students %></div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">Total Courses:</div>
  <div class="panel-body"><%= @total_courses %></div>
</div>
<% if (@last_enroolment) %>
<div class="panel panel-default">
  <div class="panel-heading">Last Enrollment:</div>
  <div class="panel-body">
    <span>Student:</span> <%= @last_enroolment.student.name %><br />
    <span>Course:</span> <%= @last_enroolment.course.name %>
  </div>
</div>
<% end %>